language: python
python:
  - "3.8"
install:
  - pip install pipenv
  - pipenv install --system --deploy --dev

script:
#  - python -m flake8
  - coverage run -m unittest discover core
  - cd backend && ./manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)