# Generated by Django 3.1.2 on 2020-10-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snack',
            new_name='SnackModel',
        ),
    ]
