# Generated by Django 3.1.2 on 2020-10-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_auto_20201009_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='snackmodel',
            name='available_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
