# Generated by Django 3.1.2 on 2020-10-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_snackmodel_available_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snackmodel',
            options={'verbose_name': 'Snack', 'verbose_name_plural': 'Snacks'},
        ),
        migrations.AlterField(
            model_name='snackmodel',
            name='available_quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade em estoque'),
        ),
        migrations.AlterField(
            model_name='snackmodel',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='snackmodel',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
    ]
